[package]
name = "xelgui"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { version = "0.30.13", features = ["wayland"] }
wgpu = "28.0"
env_logger = "0.10"
pollster = "0.4"
glam = { version = "0.28", features = ["bytemuck"] }
bytemuck = { version = "1.24", features = ["derive"] }
fontdue = "0.9"

[dependencies.image]
version = "0.24"
# default-features = false
features = ["png", "jpeg"]
